### ISSUE TITLE
Kotlin Multiplatform library

### ISSUE THREAD

**Issue by LouisCAD** [material-foundation/material-color-utilities#64] opened 2022-10-24 18:34 UTC
Hello, it'd be cool to support Kotlin Multiplatform as there are already apps with their UI implemented in Kotlin on both iOS and Android.

Making it can be fairly easy as you can start by converting the Java code to Kotlin before improving the API and ensuring you don't depend on JVM only APIs.

**Comment by CLOVIS-AI** [comment] 2022-12-11 22:22
If the maintainers want to maintain this in the future, I'm willing to help with the migration.

**Comment by guidezpl** [comment] 2023-02-09 12:22
Unfortunately due to resourcing constraints, we likely won't be able to do this, although I'm trying to convince decision makers to open this repo up for contributions so that the community can add features such as this.

Since this issue is a duplicate of https://github.com/material-foundation/material-color-utilities/issues/54, closing

**Closed by guidezpl** 2023-02-09 12:22 UTC
Labels: library: new
